version: '3'
services:

  facade:
    build: facade
    image: facade
    container_name: facadetest
    ports:
      - "8080:8080"

  account:
    build: account
    image: account
    container_name: accounttest

  payment:
    build: payment
    image: payment
    container_name: paymenttest

  token:
    build: token
    image: token
    container_name: tokentest

  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitmq__container
    ports:
      - "5673:5672"
      - "15673:15672"