version: '3'
services:
  facade:
    build: Facade
    image: Facade
    container_name: Facade
    ports:
      - "8080:8080"
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"