version: '3'
services:
  facade:
    build: facade
    image: facade
    container_name: facade
    ports:
      - "8080:8080"
  payment_ms:
    build: payment_ms
    image: payment_ms
    container_name: payment_ms
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"