swagger: "2.0"
info:
  description: "This is a DTUPay server public REST API endpoints."
  version: ""
  title: "DTUPay - Group 18"
  termsOfService: ""
tags:
  - name: "Merchant"
  - name: "Customer"
  - name: "Manager"
paths:
  /manager/report:
    post:
      tags:
        - "Manager"
      summary: "Request a payment Report"
      description: ""
      operationId: "manager report"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        "202":
          description: "Successful Response"
          schema:
            type: string
            example: ["sum":"1500", "payments": [{"token": "[@SG3ds3SDF3", "marchantId": "h45h8j8c7c5x", "amount": "500"},{"token": "[@sd4Df4g67", "marchantId": "d8sd7f5f4s5s", "amount": "1000"}]]
        "408":
          description: "Request Timeout"
  /merchant:
    post:
      tags:
        - "Merchant"
      summary: "Register a new merchant account to DTUPay"
      description: ""
      operationId: "register merchant"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "DTUPayAccount object that needs to be registered to the DTUPay"
          required: true
          schema:
            $ref: "#/definitions/DTUPayAccountNew"
      responses:
        "202":
          description: "Successful Response"
          schema:
            $ref: "#/definitions/DTUPayAccount"
        "408":
          description: "Request Timeout"
        "400":
          description: "An account with given bank account number already exists"
  /merchant/payment:
    post:
      tags:
        - "Merchant"
      summary: "Create a payment via DTUPay"
      description: ""
      operationId: "create payment"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Payment object"
          required: true
          schema:
            $ref: "#/definitions/Payment"
      responses:
        "202":
          description: "Successful Payment!"
        "408":
          description: "Request Timeout"
        "400":
          description: "An account with given bank account number already exists"
  /merchant/{cid}:
    delete:
      tags:
        - "Merchant"
      summary: "Remove a merchant account from DTUPay"
      description: ""
      operationId: "remove merchant"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "cid"
          in: "path"
          description: "ID of merchant to be removed"
          required: true
          type: "string"
      responses:
        "202":
          description: "Account with id: d7sd6sd5f5tf5vt5v4s6 is successfully deleted"
        "408":
          description: "Request Timeout"
        "400":
          description: "Account doesn't exists"
  /merchant/report/{mid}:
    post:
      tags:
        - "Merchant"
      summary: "Request a payment Report"
      description: ""
      operationId: "merchant report"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "mid"
          in: "path"
          description: "ID of merchant"
          required: true
          type: "string"
      responses:
        "202":
          description: "Successful Response"
          schema:
            type: string
            example: [{"token": "[@SG3ds3SDF3", "marchantId": "h45h8j8c7c5x", "amount": "500"},{"token": "[@sd4Df4g67", "marchantId": "d8sd7f5f4s5s", "amount": "1000"}]
        "408":
          description: "Request Timeout"
  /customer:
    post:
      tags:
        - "Customer"
      summary: "Register a new customer account to DTUPay"
      description: ""
      operationId: "register customer"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "DTUPayAccount object that needs to be registered to the DTUPay"
          required: true
          schema:
            $ref: "#/definitions/DTUPayAccountNew"
      responses:
        "202":
          description: "Successful Response"
          schema:
            $ref: "#/definitions/DTUPayAccount"
        "408":
          description: "Request Timeout"
        "400":
          description: "An account with given bank account number already exists"
  /customer/{mid}:
    delete:
      tags:
        - "Customer"
      summary: "Remove a customer account from DTUPay"
      description: ""
      operationId: "remove customer"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "mid"
          in: "path"
          description: "ID of customer to be removed"
          required: true
          type: "string"
      responses:
        "202":
          description: "Account with id: d7sd6sd5f5tf5vt5v4s6 is successfully deleted"
        "408":
          description: "Request Timeout"
        "400":
          description: "Account doesn't exists"
  /customer/report/{cid}:
    post:
      tags:
        - "Customer"
      summary: "Request a payment Report"
      description: ""
      operationId: "customer report"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "cid"
          in: "path"
          description: "ID of customer"
          required: true
          type: "string"
      responses:
        "202":
          description: "Successful Response"
          schema:
            type: string
            example: [{"token": "[@SG3ds3SDF3", "marchantId": "h45h8j8c7c5x", "amount": "500"},{"token": "[@sd4Df4g67", "marchantId": "d8sd7f5f4s5s", "amount": "1000"}]
        "408":
          description: "Request Timeout"
  /customer/token/{cid}/{amount}:
    post:
      tags:
        - "Customer"
      summary: "Create new customer tokens by amount"
      description: ""
      operationId: "create the amount of tokens requested for a customer"
      produces:
        - "application/json"
      parameters:
        - name: "cid"
          in: "path"
          description: "ID of customer"
          required: true
          type: "string"
        - name: "amount"
          in: "path"
          description: "How many tokens to produce"
          required: true
          type: "string"
      responses:
        "200":
          description: "Successful Response"
          schema:
            type: string
            example: ["token 1", "token 2", "token 3"]
        "408":
          description: "Request Timeout"
        "400":
          description: |
            + Customer ran out of tokens!
            + Customer requests too many tokens!
            + Customer has sufficient tokens and cannot request more!
  /customer/token/{cid}:
    get:
      tags:
        - "Customer"
      summary: "Retrieve all customer tokens"
      description: ""
      operationId: "retrieve all customer tokens"
      produces:
        - "application/json"
      parameters:
        - name: "cid"
          in: "path"
          description: "ID of customer"
          required: true
          type: "string"
      responses:
        "200":
          description: "Successful Response"
          schema:
            type: string
            example: ["token 1", "token 2", "token 3"]
        "408":
          description: "Request Timeout"
        "400":
          description: |
            + Customer ran out of tokens!
            + Customer requests too many tokens!
            + Customer has sufficient tokens and cannot request more!
definitions:
  DTUPayAccount:
    type: "object"
    required:
      - "id"
      - "name"
      - "cpr"
      - "dtuBankAccount"
    properties:
      id:
        type: "string"
        example: "6df6d7s6s54a3d"
      name:
        type: "string"
        example: "John Doe"
      cpr:
        type: "string"
        example: "01012001-1234"
      dtuBankAccount:
        type: "string"
        example: "a1s2de2jd9-3dk393jo9s-d7e83kd03l"
    xml:
      name: "DTUPayAccount"
  DTUPayAccountNew:
    type: "object"
    required:
      - "id"
      - "name"
      - "cpr"
      - "dtuBankAccount"
    properties:
      id:
        type: "string"
        example: ""
      name:
        type: "string"
        example: "John Doe"
      cpr:
        type: "string"
        example: "01012001-1234"
      dtuBankAccount:
        type: "string"
        example: "a1s2de2jd9-3dk393jo9s-d7e83kd03l"
    xml:
      name: "DTUPayAccountNew"
  Payment:
    type: "object"
    required:
      - "token"
      - "mid"
      - "amount"
    properties:
      token:
        type: "string"
        example: "2dd56we8f9v7b6c0xs8f6v5b4"
      mid:
        type: "string"
        example: "s8ddf5a8s9df8d6s5a7s8f7d5"
      amount:
        type: "string"
        example: "1000"
    xml:
      name: "Payment"